"""Add image_url to Product

Revision ID: 105eb30c7be1
Revises: 3ed63049b247
Create Date: 2025-10-18 21:54:47.781061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '105eb30c7be1'
down_revision = '3ed63049b247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
