"""Add is_delivered column to Product

Revision ID: 1adcfb7f7860
Revises: 105eb30c7be1
Create Date: 2025-10-19 10:30:51.819223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adcfb7f7860'
down_revision = '105eb30c7be1'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('market_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_delivered', sa.Boolean(), nullable=False, server_default=sa.text('0')))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_product', schema=None) as batch_op:
        batch_op.drop_column('is_delivered')

    # ### end Alembic commands ###
