"""Add reminder log table

Revision ID: 3828cbec94de
Revises: 0bf92d4fde91
Create Date: 2025-06-07 11:21:24.624470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3828cbec94de'
down_revision = '0bf92d4fde91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('booking_uuid', sa.String(length=36), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_uuid'], ['booking.uuid'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_uuid', 'booking_uuid', name='uq_reminder_once')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder_log')
    # ### end Alembic commands ###
