"""Add uuid column to reminder_log with named constraint

Revision ID: 866144e8ccd9
Revises: 3828cbec94de
Create Date: 2025-06-08 18:02:19.489611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866144e8ccd9'
down_revision = '3828cbec94de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint('uq_reminderlog_uuid', ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_reminderlog_uuid', type_='unique')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
