# app/models/booking.py
# 
# Author: Indrajit Ghosh
# Created On: May 10, 2025
# 
import uuid
from app.extensions import db

class TimeSlot(db.Model):
    __tablename__ = 'timeslot'

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String(36), unique=True, nullable=False, default=lambda: uuid.uuid4().hex)
    machine_id = db.Column(db.Integer, db.ForeignKey('washingmachine.id'), nullable=False)
    slot_number = db.Column(db.Integer, nullable=False)  # 1, 2, 3, 4
    time_range = db.Column(db.String(20), nullable=False, default="00:00-00:00")

    machine = db.relationship("WashingMachine", back_populates="time_slots")
    bookings = db.relationship("Booking", back_populates="time_slot", cascade="all, delete-orphan")

    def to_json(self):
        return {
            "uuid": self.uuid,
            "slot_number": self.slot_number,
            "time_range": self.time_range
        }
    
    @classmethod
    def from_json(cls, data):
        return cls(
            uuid=data["uuid"],
            slot_number=data["slot_number"],
            time_range=data["time_range"]
        )


class Booking(db.Model):
    __tablename__ = 'booking'

    id = db.Column(db.Integer, primary_key=True)
    uuid = db.Column(db.String(36), unique=True, nullable=False, default=lambda: uuid.uuid4().hex)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    time_slot_id = db.Column(db.Integer, db.ForeignKey('timeslot.id'), nullable=False)
    date = db.Column(db.Date, nullable=False)

    user = db.relationship("User", back_populates="bookings")
    time_slot = db.relationship("TimeSlot", back_populates="bookings")

    __table_args__ = (
        db.UniqueConstraint('time_slot_id', 'date', name='unique_slot_per_day'),
    )

    def to_json(self):
        """
        Convert the Booking instance into a JSON-serializable dictionary.

        Returns:
            dict: A dictionary representation of the booking, including:
                - uuid (str): UUID of the booking.
                - user_uuid (str): UUID of the associated user.
                - time_slot_uuid (str): UUID of the associated time slot.
                - date (str): Booking date in ISO format (YYYY-MM-DD).
        """
        return {
            "uuid": self.uuid,
            "user_uuid": self.user.uuid if self.user else None,
            "time_slot_uuid": self.time_slot.uuid if self.time_slot else None,
            "date": self.date.isoformat() if self.date else None,
        }

    @classmethod
    def from_json(cls, data, user_lookup, time_slot_lookup):
        """
        Create a Booking instance from a JSON dictionary.

        Args:
            data (dict): JSON dictionary typically generated by `to_json()`.
            user_lookup (dict): Mapping of user UUID (str) to User instances.
            time_slot_lookup (dict): Mapping of time slot UUID (str) to TimeSlot instances.

        Returns:
            Booking: A new Booking instance with attributes populated from `data`,
                     including valid User and TimeSlot instances resolved via lookups.
                     The instance is not yet added to the database session.

        Raises:
            ValueError: If the user_uuid or time_slot_uuid is not found in the respective lookup dictionaries.
        
        Usage:
            Prepare the lookups before import:
                users = User.query.all()
                user_lookup = {u.uuid: u for u in users}
                slots = TimeSlot.query.all()
                time_slot_lookup = {ts.uuid: ts for ts in slots}

            Then import:
                booking = Booking.from_json(json_data, user_lookup, time_slot_lookup)
        """
        user = user_lookup.get(data["user_uuid"])
        if not user:
            raise ValueError(f"User with UUID {data['user_uuid']} not found for Booking import")

        time_slot = time_slot_lookup.get(data["time_slot_uuid"])
        if not time_slot:
            raise ValueError(f"TimeSlot with UUID {data['time_slot_uuid']} not found for Booking import")

        return cls(
            uuid=data["uuid"],
            user=user,
            time_slot=time_slot,
            date=data.get("date"),
        )

